#!/bin/bash
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# Mixar Build Script
# Builds Blender (always Release) + Mixar (environment from settings.sh)

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Use MIXAR_ENV directly from settings.sh (already exported there)
# Blender always builds in Release mode for optimal performance
BLENDER_BUILD_ENV="Release"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${MIXAR_ENV}"

# Overlay Mixar sources onto source
echo "Overlaying Mixar sources onto source..."
"$SCRIPT_DIR/overlay.sh"

# Configure build directory
mkdir -p "${BUILD_ENV_DIR}"

# Generate environment configuration header
echo "Generating environment configuration for: $MIXAR_ENV"
mkdir -p "$SOURCE_DIR/source/creator"
cat > "$SOURCE_DIR/source/creator/mixar_env_config.h" << EOF
#pragma once
// Auto-generated file - DO NOT EDIT
// Generated for environment: $MIXAR_ENV

#define MIXAR_BASE_URL "$MIXAR_BACKEND_URL"
#define MIXAR_FRONTEND_BASE_URL "$MIXAR_FRONTEND_URL"
#define MIXAR_CURRENT_ENV "$MIXAR_ENV"

// Environment-specific macros for conditional compilation
EOF

# Generate environment-specific macro based on current MIXAR_ENV
case "$MIXAR_ENV" in
    "Prod")
        echo "#define MIXAR_ENV_PROD" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "Dev")
        echo "#define MIXAR_ENV_DEV" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    "UAT"|"Uat")
        echo "#define MIXAR_ENV_UAT" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
    *)
        echo "#define MIXAR_ENV_PROD  // Default to production for unknown environment" >> "$SOURCE_DIR/source/creator/mixar_env_config.h"
        ;;
esac

# Emit the build-frozen Python env marker (mirrors mixar_env_config.h on the
# Python side). Used by mixar.config.config.get_dev_bypass_credentials() to
# gate the dev bypass behind a value that cannot be flipped by editing the
# bundled mixar.json. Only Dev builds get DEV_BYPASS_ALLOWED=True.
if [ "$MIXAR_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/mixar/config"
cat > "$SOURCE_DIR/scripts/mixar/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$MIXAR_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

# Drop cache entries that resolved into a different SDK than the one we build
# against. CMake never re-runs find_library() for an already-cached variable,
# so a cache configured without SDKROOT keeps its Command Line Tools framework
# paths forever. Those live outside -isysroot, so CMake passes them as explicit
# -F paths, which demotes their headers from system to user headers and lets
# -Werror=unguarded-availability-new fail the Cycles Metal build. Purging by
# value re-resolves them on this configure; the deployment-target gap that
# actually trips the warning is unchanged.
# Matches on whole SDK paths rather than a value prefix: entries such as
# *_LIB_DEPENDS legitimately list several correct SDK paths mid-value, and a
# prefix test flags every one of them on an already-healthy cache.
CMAKE_CACHE_FILE="$BUILD_ENV_DIR/CMakeCache.txt"
if [[ "$PLATFORM" == "macOS" && -n "${SDKROOT:-}" && -f "$CMAKE_CACHE_FILE" ]]; then
    STALE_SDK_VARS=()
    while read -r cache_var; do
        [[ -n "$cache_var" ]] && STALE_SDK_VARS+=("-U$cache_var")
    done < <(
        grep -E '^[A-Za-z_0-9]+:[A-Z]+=' "$CMAKE_CACHE_FILE" \
            | awk -v sdk="$SDKROOT" '
                {
                    var = $0; sub(/:.*/, "", var); rest = $0; stale = 0
                    while (match(rest, /\/[^ ";=[\]]*SDKs\/MacOSX[^ ";=[\]\/]*\.sdk/)) {
                        if (substr(rest, RSTART, RLENGTH) != sdk) stale = 1
                        rest = substr(rest, RSTART + RLENGTH)
                    }
                    if (stale) print var
                }' \
            | sort -u
    )
    if (( ${#STALE_SDK_VARS[@]} > 0 )); then
        echo "Purging ${#STALE_SDK_VARS[@]} CMake cache entries resolved outside $SDKROOT"
        cmake -S "$SOURCE_DIR" -B "$BUILD_ENV_DIR" "${STALE_SDK_VARS[@]}" >/dev/null
    fi
fi

# Configure with CMake (all platform logic handled in settings.sh)
echo "Configuring Mixar build - Blender: $BLENDER_BUILD_ENV, Mixar Environment: $MIXAR_ENV for $PLATFORM..."
cmake -C "$CMAKE_DIR/mixar_overrides.cmake" \
    $CMAKE_GENERATOR_ARGS \
    -S "$SOURCE_DIR" \
    -B "$BUILD_ENV_DIR" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# Build (all platform-specific args handled in settings.sh)
echo "Building Blender in $BLENDER_BUILD_ENV mode for Mixar environment: $MIXAR_ENV"
echo "Using $BUILD_CORES cores for parallel build"
cmake --build "$BUILD_ENV_DIR" $BUILD_ARGS
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV"

# Generate runtime configuration for the bundle
echo "Generating runtime configuration for bundle..."
BUNDLE_CONFIG_DIR="$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources/$BLENDER_VERSION/config"
python3 "$ROOT_DIR/scripts/generate_config.py" --output "$BUNDLE_CONFIG_DIR/mixar.json"

# Install Python packages using the generated Python binary
echo "Installing Python packages for Mixar..."

# Determine base path for embedded Python based on platform
if [[ "$PLATFORM" == "macOS" ]]; then
    PY_BASE="$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources"
elif [[ "$PLATFORM" == "Linux" ]]; then
    PY_BASE="$BUILD_ENV_DIR/bin"
else
    echo "Error: Unsupported platform: $PLATFORM"
    exit 1
fi

# Try common python binary names inside Blender's embedded Python
PYTHON_BIN=""
for candidate in \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python${PYTHON_VERSION}" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python3" \
    "$PY_BASE/$BLENDER_VERSION/python/bin/python"; do
    if [[ -x "$candidate" ]]; then
        PYTHON_BIN="$candidate"
        break
    fi
done

SITE_PACKAGES="$PY_BASE/$BLENDER_VERSION/python/lib/python${PYTHON_VERSION}/site-packages"
REQUIREMENTS_FILE="$(dirname "$SCRIPT_DIR")/python_requirements.txt"

if [[ -n "$PYTHON_BIN" ]]; then
    echo "Found Python binary: $PYTHON_BIN"
    mkdir -p "$SITE_PACKAGES"
    
    # Check if requirements file exists
    if [[ -f "$REQUIREMENTS_FILE" ]]; then
        echo "Installing packages from: $REQUIREMENTS_FILE"
        
        # Force pip to install to the embedded Python's site-packages
        # Use --no-user to prevent installation to user site-packages
        # Use --target to specify the exact location
        if "$PYTHON_BIN" -m pip install --no-user --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
            echo "Successfully installed Python packages to embedded Python site-packages"
            # truststore is what lets the app trust corporate root CAs; a
            # silent fallback to certifi would only surface at a customer.
            if ! "$PYTHON_BIN" -c "import truststore" 2>/dev/null; then
                echo "Error: truststore installed but not importable from the embedded Python"
                exit 1
            fi
        elif command -v pip3 >/dev/null 2>&1; then
            echo "Embedded pip failed, trying system pip with --target..."
            if pip3 install --target "$SITE_PACKAGES" -r "$REQUIREMENTS_FILE"; then
                echo "Successfully installed Python packages using system pip"
            else
                echo "Warning: Failed to install Python packages from requirements file"
            fi
        else
            echo "Warning: No pip available, skipping Python package installation"
        fi
    else
        echo "Warning: Requirements file not found at: $REQUIREMENTS_FILE"
        exit 1
    fi
else
    echo "Warning: Python binary not found under: $PY_BASE/$BLENDER_VERSION/python/bin"
fi

# Re-sign the dev build with a stable identity so macOS Keychain "Always
# Allow" persists across rebuilds (opt-in via MIXAR_DEV_SIGN_ID in .env; see
# scripts/unix/setup_dev_codesign.sh). Without this the linker's ad-hoc
# signature changes every build, and Keychain re-prompts for the
# MixarSafeStorage login tokens on each rebuild. Only the main executable is
# signed — the process's code identity is what Keychain ACLs match on.
# Release/notarization signing lives in package.sh and is unaffected.
if [[ "$PLATFORM" == "macOS" && -n "${MIXAR_DEV_SIGN_ID:-}" ]]; then
    MIXAR_APP_BINARY="$BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"
    # get-task-allow keeps the binary attachable by lldb, matching what an
    # ad-hoc dev signature allows.
    DEV_SIGN_ENTITLEMENTS="$BUILD_ENV_DIR/dev_codesign_entitlements.plist"
    cat > "$DEV_SIGN_ENTITLEMENTS" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.get-task-allow</key>
    <true/>
</dict>
</plist>
EOF
    echo "Signing dev build with identity: $MIXAR_DEV_SIGN_ID"
    if codesign --force --sign "$MIXAR_DEV_SIGN_ID" \
        --entitlements "$DEV_SIGN_ENTITLEMENTS" "$MIXAR_APP_BINARY"; then
        echo "Dev codesign OK — Keychain 'Always Allow' will persist across rebuilds."
    else
        echo "Warning: dev codesign failed. The build is still usable, but Keychain"
        echo "will re-prompt after every rebuild. Create the identity with:"
        echo "  ./scripts/unix/setup_dev_codesign.sh"
    fi
fi

# Done
echo "=== Build Complete ==="
echo "Python packages installed from: $REQUIREMENTS_FILE"
echo "Run Mixar using: $BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"