#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

set -euo pipefail

# Load all settings from settings.sh
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/settings.sh"

# Define build directory for this environment
BUILD_ENV_DIR="${BUILD_DIR}/${MIXAR_ENV}"
BLENDER_BUILD_ENV="Release"

echo "Clearing previous source directory..."
cd "$ROOT_DIR"
rm -rf "$SOURCE_DIR/scripts"
# rm -rf "$BUILD_ENV_DIR/bin/Mixar.app/Contents/Resources/scripts"
mkdir -p "$SOURCE_DIR/scripts"

rsync -a "$UPSTREAM_DIR/scripts/" "$SOURCE_DIR/scripts/"

echo "Overlaying Mixar scripts onto source..."
rsync -av "$SRC_DIR/scripts/" "$SOURCE_DIR/scripts/"

# The scripts tree was just recreated, so re-emit the build-frozen Python env
# marker exactly as build.sh does (mixar.config.config reads DEV_BYPASS_ALLOWED
# from it; without the file a Dev bundle falls back to browser SSO login).
if [ "$MIXAR_ENV" = "Dev" ]; then
    BUILD_ENV_DEV_BYPASS="True"
else
    BUILD_ENV_DEV_BYPASS="False"
fi
mkdir -p "$SOURCE_DIR/scripts/mixar/config"
cat > "$SOURCE_DIR/scripts/mixar/config/_build_env.py" << EOF
# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
# Auto-generated by scripts/unix/build.sh - DO NOT EDIT
BUILD_ENVIRONMENT = "$MIXAR_ENV"
DEV_BYPASS_ALLOWED = $BUILD_ENV_DEV_BYPASS
EOF

echo "Installing scripts using CMake..."
cmake --build "$BUILD_ENV_DIR" --target install --config "$BLENDER_BUILD_ENV"

echo "Scripts installation complete."

# The install target re-copies the executable ad-hoc signed; restore the
# stable dev signature (no-op unless MIXAR_DEV_SIGN_ID is set in .env).
"$SCRIPT_DIR/dev_codesign.sh" "$BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"
echo "Run Mixar using: $BUILD_ENV_DIR/bin/Mixar.app/Contents/MacOS/Mixar"