# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
# SPDX-License-Identifier: GPL-2.0-or-later
"""Real Eevee reflection-only exclusion fixture, driven through the QA server."""
from pathlib import Path


def run(qa, output_directory):
    output = Path(output_directory)
    return qa.cmd("eval", _sock_timeout=60, code=(
        "import math\n"
        "from mixar.modules.common.render_visibility.result import read_result\n"
        "previous = bpy.context.scene\n"
        "s = bpy.data.scenes.new('Visibility Reflection QA')\n"
        "bpy.context.window.scene = s\n"
        "s.render.engine = 'BLENDER_EEVEE'\n"
        "s.render.use_compositing = False\n"
        "s.render.use_sequencer = False\n"
        "s.render.resolution_x = s.render.resolution_y = 256\n"
        "s.render.resolution_percentage = 100\n"
        "s.eevee.taa_render_samples = 32\n"
        "s.eevee.use_raytracing = True\n"
        "s.world = bpy.data.worlds.new('Reflection QA world')\n"
        "s.world.use_nodes = True\n"
        "s.world.node_tree.nodes['Background'].inputs[0].default_value = (0.08, 0.08, 0.08, 1)\n"
        "camera_data = bpy.data.cameras.new('Reflection QA camera')\n"
        "camera = bpy.data.objects.new('Reflection QA camera', camera_data)\n"
        "s.collection.objects.link(camera)\n"
        "camera.location = (0, -12, 0)\n"
        "camera.rotation_euler = (math.pi / 2, 0, 0)\n"
        "camera_data.type = 'ORTHO'\n"
        "camera_data.ortho_scale = 6\n"
        "s.camera = camera\n"
        "bpy.ops.mesh.primitive_plane_add(size=4, rotation=(math.pi / 2, 0, 0))\n"
        "mirror = bpy.context.object\n"
        "mirror.name = 'QA_Mirror'\n"
        "mat = bpy.data.materials.new('QA Mirror material')\n"
        "mat.use_nodes = True\n"
        "bsdf = mat.node_tree.nodes['Principled BSDF']\n"
        "bsdf.inputs['Base Color'].default_value = (1, 1, 1, 1)\n"
        "bsdf.inputs['Metallic'].default_value = 1\n"
        "bsdf.inputs['Roughness'].default_value = 0\n"
        "mirror.data.materials.append(mat)\n"
        "bpy.ops.mesh.primitive_uv_sphere_add(radius=0.9, location=(0, -16, 0))\n"
        "target = bpy.context.object\n"
        "target.name = 'QA_ReflectionOnly'\n"
        "target_mat = bpy.data.materials.new('QA Reflection source')\n"
        "target_mat.use_nodes = True\n"
        "bsdf = target_mat.node_tree.nodes['Principled BSDF']\n"
        "bsdf.inputs['Emission Color'].default_value = (1, 0.08, 0, 1)\n"
        "bsdf.inputs['Emission Strength'].default_value = 2\n"
        "target.data.materials.append(target_mat)\n"
        "probe_data = bpy.data.lightprobes.new('QA Planar probe', 'PLANE')\n"
        "probe_data.influence_distance = 30\n"
        "probe = bpy.data.objects.new('QA Planar probe', probe_data)\n"
        "s.collection.objects.link(probe)\n"
        "probe.location = (0, -0.05, 0)\n"
        "probe.rotation_euler = (math.pi / 2, 0, 0)\n"
        "probe.scale = (3, 3, 3)\n"
        f"s.render.filepath = {str(output / 'reflection.png')!r}\n"
        "try:\n"
        "    bpy.ops.render.render(write_still=True, capture_visible_objects=True)\n"
        "    reflected = read_result(s)\n"
        "    assert {o['name'] for o in reflected['objects']} == {mirror.name}, reflected\n"
        "    mirror.name = 'QA_RefractiveSurface'\n"
        "    target.name = 'QA_RefractionOnly'\n"
        "    target.location = (0, 2, 0)\n"
        "    bsdf = mat.node_tree.nodes['Principled BSDF']\n"
        "    bsdf.inputs['Metallic'].default_value = 0\n"
        "    bsdf.inputs['Transmission Weight'].default_value = 1\n"
        "    bsdf.inputs['IOR'].default_value = 1.45\n"
        "    mat.use_raytrace_refraction = True\n"
        f"    s.render.filepath = {str(output / 'refraction.png')!r}\n"
        "    bpy.ops.render.render(write_still=True, capture_visible_objects=True)\n"
        "    refracted = read_result(s)\n"
        "    assert {o['name'] for o in refracted['objects']} == {mirror.name}, refracted\n"
        "    result = {'reflection': reflected, 'refraction': refracted}\n"
        "finally:\n"
        "    bpy.context.window.scene = previous\n"
    ))
