# SPDX-FileCopyrightText: 2025 Mixar Authors
#
# SPDX-License-Identifier: GPL-2.0-or-later

"""Moodboard clipboard operators.

Hosts the Copy operator that writes the first selected moodboard image to
the system clipboard as a PNG. The Paste operator already lives in
``image_ops.py``; this module is split out to keep both files under the
500-line limit and to group platform-specific clipboard code in one place.

"Selected" here means what ``media_utils.selected_exportable_media`` means: a
generated result is owned by its inference node and is never ``selected``
itself, so copying resolves THROUGH the selected node to the image or video it
produced. That is the whole of Ctrl/Cmd+C on this canvas -- nodes themselves
duplicate with Shift+D, and there is no separate node clipboard to keep in
step with this one.
"""

import bpy
from bpy.types import Operator

from mixar.config.logging_config import get_logger
from ....common.utils.platform_utils import format_shortcut
from ...core.moodboard_clipboard import copy_selected
from ...core.media_utils import is_video_item, selected_exportable_media
from ...core.system_clipboard import copy_blender_image_to_system_clipboard

logger = get_logger(__name__)


def _selected_moodboard_image(scene):
    """Return the first selected still suitable for the system clipboard.

    Resolves through selected nodes as well, so copying a finished Generate
    card puts its picture on the OS clipboard like any other selected still.
    """
    for item in selected_exportable_media(scene):
        if not is_video_item(item):
            return item
    return None


def _has_moodboard_selection(scene):
    """True if any moodboard media (a node's result included) or text box is
    selected."""
    if selected_exportable_media(scene):
        return True
    textboxes = getattr(scene, "mixie_moodboard_textboxes", None)
    return bool(textboxes) and any(tb.selected for tb in textboxes)


class MIXIE_OT_moodboard_copy_image(Operator):
    """Copy the selected moodboard media and text box(es) so they can be pasted"""

    bl_idname = "mixie.moodboard_copy_image"
    bl_label = "Copy"
    bl_description = (
        f"Copy the selected images, videos and text boxes, including the "
        f"result generated by a selected node; paste with "
        f"{format_shortcut('V')}"
    )
    bl_options = {'REGISTER'}

    @classmethod
    def poll(cls, context):
        return _has_moodboard_selection(context.scene)

    def execute(self, context):
        scene = context.scene

        # Primary path: snapshot the selection into the reliable in-app
        # clipboard so paste is a lossless, cross-platform duplicate.
        count = copy_selected(scene)
        if count == 0:
            self.report({'WARNING'}, "Nothing selected to copy")
            return {'CANCELLED'}

        # Secondary, best-effort: put the first still image on the system
        # clipboard. Movies remain lossless in the in-app clipboard; exporting
        # them to an OS image clipboard would silently reduce them to one frame.
        item = _selected_moodboard_image(scene)
        if item is not None and item.image is not None:
            try:
                copy_blender_image_to_system_clipboard(item.image, scene)
            except Exception as e:
                logger.debug(f"System clipboard copy skipped: {e}")

        noun = "item" if count == 1 else "items"
        self.report({'INFO'}, f"Copied {count} {noun}")
        return {'FINISHED'}


classes = (
    MIXIE_OT_moodboard_copy_image,
)
