# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Mixar Configuration Utilities

Provides centralized configuration loading for all Mixar modules.
"""

import os
import json
import tempfile
import time
import bpy

from .logging_config import get_logger

logger = get_logger(__name__)


UI_MODE_AI = "ai"
UI_MODE_PRO = "pro"
_UI_MODES = (UI_MODE_AI, UI_MODE_PRO)


def get_config_path():
    """Get the path to the config file"""
    return os.path.join(bpy.utils.resource_path('LOCAL'), 'config', 'mixar.json')


def _backup_corrupt_config(config_path, error):
    """Move a corrupt config file aside (mixar.json.corrupt-<ts>) so reads can
    rebuild from defaults and the next write cannot erase its contents."""
    stamp = time.strftime('%Y%m%d-%H%M%S')
    backup_path = '%s.corrupt-%s' % (config_path, stamp)
    counter = 1
    while os.path.exists(backup_path):
        # Same-second collision: never clobber an earlier backup.
        backup_path = '%s.corrupt-%s.%d' % (config_path, stamp, counter)
        counter += 1
    try:
        os.replace(config_path, backup_path)
        logger.error("Corrupt config %s (%s); backed up to %s, rebuilding "
                     "from defaults", config_path, error, backup_path)
    except OSError as exc:
        logger.error("Corrupt config %s (%s); could not back up to %s: %s",
                     config_path, error, backup_path, exc)


def _read_config_file(config_path, warn_missing=False):
    """Parse the config file. Returns a dict; {} when missing or corrupt.

    A corrupt file is backed up and treated as missing so reads rebuild
    from defaults instead of failing, and so the next write cannot erase
    the keys that could not be parsed."""
    try:
        with open(config_path, 'r') as f:
            config = json.load(f)
    except FileNotFoundError:
        if warn_missing:
            logger.warning("Config file not found at: %s", config_path)
        return {}
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        _backup_corrupt_config(config_path, e)
        return {}
    except Exception as e:
        logger.error("Error loading config: %s", e)
        return {}
    if not isinstance(config, dict):
        # Valid JSON but not an object -- unusable as config, same treatment.
        _backup_corrupt_config(config_path, "not a JSON object")
        return {}
    return config


def load_mixar_config():
    """Load Mixar configuration from JSON file"""
    try:
        return _read_config_file(get_config_path(), warn_missing=True)
    except Exception as e:
        logger.error("Error loading config: %s", e)
        return {}


# Global config instance
_config = None


def get_config():
    """Get the global configuration, loading it if necessary"""
    global _config
    if _config is None:
        _config = load_mixar_config()
    return _config

def add_config(key, value):
    """Add a key-value pair to the global configuration and persist to file"""
    global _config
    if _config is None:
        _config = load_mixar_config()
    _config[key] = value

    # Persist to file, merging over what is currently on disk so keys this
    # process did not parse (e.g. after a corrupt read) or that changed since
    # the last load are not silently erased by a write of only the caller's
    # keys. In-memory values win for keys present in both.
    try:
        config_path = get_config_path()
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        merged = {**_read_config_file(config_path), **_config}
        _write_config_file(config_path, merged)
        return True
    except Exception as e:
        logger.error("Error saving config: %s", e)
        return False


def _write_config_file(config_path, config):
    """Atomically write the config file (mkstemp + os.replace, the Mixar
    idiom) so a crash mid-write cannot leave a corrupt mixar.json behind."""
    fd, tmp_path = tempfile.mkstemp(
        dir=os.path.dirname(config_path), prefix='.mixar.json.', suffix='.tmp'
    )
    try:
        with os.fdopen(fd, 'w') as f:
            json.dump(config, f, indent=2)
        os.replace(tmp_path, config_path)
    except Exception:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass
        raise


def get_environment():
    """Get the current environment from config"""
    config = get_config()
    return config.get('environment', 'Prod')


def get_server_url():
    """Get the API server URL (resolved at build time via env vars)."""
    config = get_config()
    return config.get('backend_url', 'https://api.mixar.app')


def get_dev_bypass_credentials() -> tuple:
    """Return (username, password) for dev bypass login, or ('', '') if disabled.

    Gated on a build-time constant in ``_build_env.py``, not on the mutable
    ``mixar.json``. The ``_build_env`` module is auto-generated by
    ``scripts/unix/build.sh`` / ``scripts/windows/build.bat`` and sets
    ``DEV_BYPASS_ALLOWED = True`` only for ``MIXAR_ENV=Dev`` builds. A user
    editing the bundled ``mixar.json`` to set ``environment=Dev`` cannot
    enable the bypass in a Prod/UAT build because the module that grants
    permission is not generated for those builds.

    Falls closed (returns ``('', '')``) when ``_build_env`` is absent — this
    is the case in source-tree imports (pytest, dev workflow before build).
    """
    try:
        from ._build_env import DEV_BYPASS_ALLOWED
    except ImportError:
        return ("", "")
    if not DEV_BYPASS_ALLOWED:
        return ("", "")
    config = get_config()
    bypass = config.get("dev_bypass", {})
    if not bypass.get("enabled", False):
        return ("", "")
    return (bypass.get("username", ""), bypass.get("password", ""))


def get_ui_mode() -> str:
    """Return the persisted UI mode. New users default to AI mode."""
    mode = get_config().get("ui_mode", UI_MODE_AI)
    return mode if mode in _UI_MODES else UI_MODE_AI


def set_ui_mode(mode: str) -> bool:
    """Persist the UI mode preference. Returns False on unknown mode or write failure."""
    if mode not in _UI_MODES:
        logger.error("Invalid ui_mode: %r", mode)
        return False
    return add_config("ui_mode", mode)


def get_frontend_url():
    """Get the frontend URL (resolved at build time via env vars).

    Used for browser-facing pages like SSO login.
    Falls back to the API server URL if frontend_url is not configured.
    """
    config = get_config()
    return config.get('frontend_url', get_server_url())
