# SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""Mirror the Python callback HTML into the native callback's embedded page."""

import json
from pathlib import Path
import runpy

ROOT = Path(__file__).resolve().parents[1]
source = ROOT / "src/scripts/mixar/modules/auth/core/sso_pages.py"
page = runpy.run_path(str(source))["SUCCESS_PAGE"].decode("utf-8")
header = """// SPDX-FileCopyrightText: 2026 Adeveda Enterprises Private Limited
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by scripts/generate_sso_success_page.py; edit sso_pages.py instead.
// Embedded Clash Grotesk: see release/datafiles/fonts/ClashGrotesk-LICENSE.txt.
#pragma once

static const char *SUCCESS_PAGE =
"""
for offset in range(0, len(page), 1000):
    header += "    " + json.dumps(page[offset:offset + 1000], ensure_ascii=False) + "\n"
header = header.rstrip() + ";\n"
(ROOT / "src/source/creator/mixar_sso_success_page.h").write_text(header, encoding="utf-8")
